version: '3.8'

services:
  database:    
    image: mariadb:10.6.20-ubi9
    container_name: fisrv-magento-db
    command: '--default-authentication-plugin=mysql_native_password'
    mem_limit: "256M"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    networks:
      - default
    volumes:
      - db:/var/lib/mysql
  opensearch:
    image: markoshust/magento-opensearch:2.5-1.4.0
    container_name: fisrv-opensearch
    hostname: opensearch
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
  magento:
    image: registry.gitlab.mherrm.de/cgi/fisrv-magento2-plugin:latest
    container_name: fisrv-magento-apache
    mem_limit: "1024M"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fisrv-magento-secure.entrypoints=http,https"
      - "traefik.http.routers.fisrv-magento-secure.rule=Host(`magento2.fisv.mherrm.de`)"
      - "traefik.http.routers.fisrv-magento-secure.tls=true"
      - "traefik.http.routers.fisrv-magento-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fisrv-magento-secure.service=fisrv-magento"
      - "traefik.http.services.fisrv-magento.loadbalancer.server.scheme=https"
      - "traefik.http.services.fisrv-magento.loadbalancer.server.port=443"
      - "traefik.docker.network=traefik"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - database
    networks:
      - default
      - traefik
networks:
  traefik:
    external: true
volumes:
  db:
